
checkout:
    post:
        - pip install -U pip setuptools virtualenv

version: 2
jobs:
  test_lakeModel:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv lake
            . lake/bin/activate
            pip install --upgrade pip
            pip install -r packages/lakeModel/requirements.txt
            py.test -vv packages/lakeModel/tests

  test_ml_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv lake
            . lake/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml_api/requirements.txt
            python -m pytest packages/ml_api/tests 

  train_and_upload_lakeModel:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: 
          name: Setup env
          command: |
            virtualenv lake
            . lake/bin/activate
            pip install -r packages/lakeModel/requirements.txt
      - run: 
          name: Publish model
          command: |
            . lake/bin/activate
            chmod +x ./scripts/publish_model.sh
            PYTHONPATH=./packages/lakeModel python3 packages/lakeModel/lakeModel/train_pipeline.py
            ./scripts/publish_model.sh ./packages/lakeModel/

workflows:
  version: 2
  test-all:
    jobs:
      - test_lakeModel
      - test_ml_api
      - train_and_upload_lakeModel
      - test_ml_api:
          requires:
            - train_and_upload_lakeModel
